### ISSUE TITLE
Getting error `Cannot find module '@actions/exec'`

### ISSUE THREAD

**Issue by ljharb** [BerniWittmann/background-server-action#109]
```
Error: Cannot find module '@actions/exec'
Require stack:
- /home/runner/work/_actions/BerniWittmann/background-server-action/v1/dist/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.526 (/home/runner/work/_actions/BerniWittmann/background-server-action/v1/webpack:/background-server-action/node_modules/@vercel/ncc/dist/ncc/@@notfound.js:1:1)
    at __nccwpck_require__ (/home/runner/work/_actions/BerniWittmann/background-server-action/v1/webpack:/background-server-action/webpack/bootstrap:20:1)
    at Object.932 (/home/runner/work/_actions/BerniWittmann/background-server-action/v1/webpack:/background-server-action/index.js:2:1)
    at __nccwpck_require__ (/home/runner/work/_actions/BerniWittmann/background-server-action/v1/webpack:/background-server-action/webpack/bootstrap:20:1)
    at /home/runner/work/_actions/BerniWittmann/background-server-action/v1/webpack:/background-server-action/webpack/startup:4:1
    at Object.<anonymous> (/home/runner/work/_actions/BerniWittmann/background-server-action/v1/dist/index.js:1955:12)
```

(You do have a lockfile, but you don't have node_modules committed, and i'd expect a webpack bundle to also be pre-built - so i'm not really sure what's going on)

**Comment by rbubley** [comment]
I see the same issue.

**Comment by BerniWittmann** [comment]
I finally had the chance to work on this repo again and this issue has been fixed in the latest version. See [latest release ](https://github.com/BerniWittmann/background-server-action/releases/tag/v1.1.0) notes with more info 

Ensure you have set `uses: BerniWittmann/background-server-action@v1` or `BerniWittmann/background-server-action@v1.1.0`

**Comment by ljharb** [comment]
Thanks!
